name: Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 requests pyinstaller

    - name: Build with PyInstaller
      run: pyinstaller --name=BookFinder --onefile --windowed main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: BookFinder
        path: dist/BookFinder.exe

  release:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: BookFinder
        path: .

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.2.0
        release_name: BookFinder v1.2.0
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./BookFinder.exe
        asset_name: BookFinder.exe
        asset_content_type: application/octet-stream
